First check in where the build process works entirely for me
- Still don't have pushbutton SD images, which may be fine for a while
- Have to manually provide an FSBL ELF location still. This will be the
case until I write a Makefile that pulls the required source code from
the XSA and builds the ELF from Xilinx source code
- Will remain the user responsibility to manually configure and build
the kernel and U-boot which I believe is more than fair. If you are
unable to build those two from the source trees (and the tags) that are
indicated, then you're probably not the target audience here anyway
- Scripted device tree generation from the Xilinx source generator works
but it is entirely the user's responsibility to modify the .dtsi files
appropriately prior to compiling them into a flattened device tree blob.
- Bitstream generation is entirely manual still at this point for a
variety of reasons. Converting from a .bit to a .bin that is compatible
with the `zynq-fpga` driver in the kernel is still a manual process for
now.
- But the whole thing should work after that. Build your kernel, build
your bootloaders, build your hardware, make sure that the constants
are set correctly, and then push the button. The build directory will
have a bootfs.armhf and a rootfs.armhf directory that you can put on an
SD card and boot.  I'm probably not going to automate SD card
generation, at least not now.
- Boot parameters are still a bit of a mystery to me - the
/boot/extlinux/extlinux.conf file seems to take priority over anything
else, including what is in the device tree (good) but I can't seem to
change them on the command line (bad).  That's probably because the
extlinux file hasn't been loaded yet - maybe there's a way to halt that
process and intervene.  Otherwise, distro boot may not be the way that I
want to go and using a boot.scr that I can override from U-boot might be
a better way, at least for now.
- This is a good day! We've got what we wanted, learned a ton, and ready
to start hacking on some hardware I think.

diff --git a/scripts/build_rootfs b/scripts/build_rootfs
--- a/scripts/build_rootfs
+++ b/scripts/build_rootfs
@@ -26,6 +26,13 @@
 # system kernel. The script attempts to verify that transparent emulation has
 # been set up for the QEMU architecture specified in the build constants.
 
+function usage () {
+    printf 'Usage: %s [ROOTFS]\n\n' "${1}"
+    printf 'Where ROOTFS is the location to build the root filesystem.\n'
+    printf 'An existing directory will be moved prior to creation.\n'
+    return 0
+}
+
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
     printf '%s\n' "Script should be executed not sourced" >&2
     return 1
@@ -52,14 +59,22 @@ if [[ ! "${trans_qemu_status}" == "enabled" ]]; then
     exit 1
 fi
 
+if [[ "$#" -eq 0 ]]; then
+    err "Too few arguments provided"
+    usage "${0}"
+    exit 1
+else
+    rootfs="${1}"
+fi
+
 # Move any old root filesystems that might exist
-rootfs="${UZED_SBC_BUILD_DIR}/rootfs.${DEBIAN_ARCH}"
 if [[ -d "${rootfs}" ]]; then
     status "Found an existing directory at ${rootfs}"
     mv "${rootfs}" "${rootfs}_$(timestamp)"
 fi
 
-status "Building Debian root filesystem"
+status "Building Debian root filesystem at ${rootfs}"
+build_log="debootstrap_$(timestamp).log"
 if ! debootstrap \
     --verbose \
     --include "${DEBIAN_INCLUDE}" \
@@ -67,7 +82,7 @@ if ! debootstrap \
     --arch "${DEBIAN_ARCH}" \
     "${DEBIAN_SUITE}" \
     "${rootfs}" \
-    "${DEBIAN_MIRROR}" >"debootstrap_$(timestamp).log" 2>&1; then
+    "${DEBIAN_MIRROR}" >"${build_log}" 2>&1; then
     err "Debootstrap first stage construction failed"
     exit 1
 else
@@ -83,10 +98,15 @@ install -m 644 "constants.sh" "${rootfs}/tmp"
 status "Building Debian second stage"
 if ! LANG=C.UTF-8 chroot "${rootfs}" "/tmp/second_stage"; then
     err "Debootstrap second stage failed"
+    # In cases where the second stage script failed, a proc might still be
+    # mounted and we would like to fail responsibly, so just attempt to umount
+    # it and suppress any warning it yields
+    umount "${rootfs}/proc" >/dev/null 2>&1
+    exit 1
 else
     status "Debootstrap second stage complete"
 fi
-# In cases where the second stage script failed, a proc might still be mounted
-# and we would like to fail responsibly, so just attempt to umount it
-umount "${rootfs}/proc" >/dev/null 2>&1
+
+# Final clean up items
+mv "${build_log}" "${rootfs}"
 
