Removed explicit dependance upon QEMU being set but added a check for transparent emulation
- Also added some comments about build scripts
- Users need to add the QEMU binary format to their constants file

diff --git a/scripts/build_rootfs b/scripts/build_rootfs
--- a/scripts/build_rootfs
+++ b/scripts/build_rootfs
@@ -1,5 +1,31 @@
 #!/bin/bash
 
+# Create and configure Debian root filesystem
+#
+# This is one of a sequence of scripts that is used to build a bootable SD
+# card image for a Microzed SoC development board. It creates and configures
+# a root filesystem containing a user account, an SSH server, essential build
+# tools, and other items from an existing Linux host. It essentially performs
+# two basic operations:
+#
+# 1) Uses whatever debootstrap package is installed on the host to perform a
+# first pass installation, which downloads many essential packages from a
+# specified Debian mirror into a rootfs subdirectory and
+#
+# 2) using QEMU transparent emulation, copies some scripts to that installation
+# subdirectory, performs a `chroot` operation, and runs the debootstrap second
+# stage operation from there. After the second stage is complete, while still in
+# the chroot environment, other configurations required to make the system
+# bootable and usable are also performed (see the second_stage shell script for
+# details).
+#
+# Note that it is incumbent that the host system be configured for QEMU
+# transparent emulation. For Debian-based systems, this is usually done by
+# installing the `binfmt-support` and `qemu-user-static` packages, but users
+# should verify that the binfmt entries were properly registered with the host
+# system kernel. The script attempts to verify that transparent emulation has
+# been set up for the QEMU architecture specified in the build constants.
+
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
     printf '%s\n' "Script should be executed not sourced" >&2
     return 1
@@ -17,13 +43,21 @@ source "constants.sh" >/dev/null 2>&1 || \
 
 command -v debootstrap >/dev/null 2>&1 || \
     { depends_on "debootstrap"; exit 1; }
-# It is up to users to install a QEMU version that is sufficiently recent enough
-# to not cause problems. 
-command -v "qemu-${QEMU_ARCH}-static" >/dev/null 2>&1 || \
-    { depends_on "qemu-${QEMU_ARCH}-static"; exit 1; }
-qemu_static="$(command -v "qemu-${QEMU_ARCH}-static")"
 
+# Add a check for QEMU transparent emulation here
+trans_qemu_status="$(head -n1 "/proc/sys/fs/binfmt_misc/${QEMU_BINFMT}" \
+                        2>/dev/null)"
+if [[ ! "${trans_qemu_status}" == "enabled" ]]; then
+    err "Transparent emulation may not be enabled for target architecture"
+    exit 1
+fi
+
+# Move any old root filesystems that might exist
 rootfs="${UZED_SBC_BUILD_DIR}/rootfs.${DEBIAN_ARCH}"
+if [[ -d "${rootfs}" ]]; then
+    status "Found an existing directory at ${rootfs}"
+    mv "${rootfs}" "${rootfs}_$(timestamp)"
+fi
 
 status "Building Debian root filesystem"
 if ! debootstrap \
@@ -52,4 +86,7 @@ if ! LANG=C.UTF-8 chroot "${rootfs}" "/tmp/second_stage"; then
 else
     status "Debootstrap second stage complete"
 fi
+# In cases where the second stage script failed, a proc might still be mounted
+# and we would like to fail responsibly, so just attempt to umount it
+umount "${rootfs}/proc" >/dev/null 2>&1
 
diff --git a/scripts/second_stage b/scripts/second_stage
--- a/scripts/second_stage
+++ b/scripts/second_stage
@@ -1,12 +1,49 @@
 #!/bin/bash
 
+# Perform a debootstrap second stage installation
+#
+# This script is intended to be called by the `build_rootfs` script as the
+# executable to run when chrooting into the first pass root filesystem that
+# debootstrap creates.  It is quite specific to the intended application and
+# uses constants to define some options that may need to change in the future,
+# notably extra packages to include during the first pass that debootstrap
+# forgets to pull down by default.
+#
+# The primary operations it performs are:
+#   * Completes the debootstrap --second-stage process from the chroot
+#     environment
+#   * Configures /etc/fstab for the expected SD card image, which is a small
+#     FAT32 filesystem that will be mounted at /boot as well as an EXT4
+#     root filesystem. This is a very common SD partition pattern used for
+#     Xilinx based embedded systems (see the relevant sections of the script for
+#     details).
+#   * Sets up a serial port with root access because we're an embedded system
+#   * Configures a wired Ethernet interface
+#   * Sets up an SSH server and instructs systemd to regenerate new SSH keys the
+#     first time the system is booted. This requires that a proc filesystem be
+#     mounted in the chroot subdirectory. If the second stage script fails for
+#     any reason, the caller should make sure that if a proc is mounted, it gets
+#     unmounted afterwards.
+#   * Creates a non-root user, with sudo access
+#   * On the way out, removes the pieces of itself left behind
+
+if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    printf '%s\n' "Script should be executed not sourced" >&2
+    return 1
+fi
+if [[ "${EUID}" -ne 0 ]]; then
+    printf '%s\n' "Script must be run as root" >&2
+    exit 1
+fi
+
 source "/tmp/common.sh" >/dev/null 2>&1 || \
     { printf '%s\n' "Could not import /tmp/common.sh" >&2; exit 1; }
 source "/tmp/constants.sh" >/dev/null 2>&1 || \
-    { printf '%s\n' "Could not import /tmp/constants.sh" >&2; exit 1; }
+    { err "Could not import /tmp/constants.sh"; exit 1; }
 
+build_log="second-stage-$(timestamp).log"
 if ! /debootstrap/debootstrap \
-    --second-stage >"second-stage-$(timestamp).log" 2>&1; then
+    --second-stage >"${build_log}" 2>&1; then
     err "Second stage failed"
 fi
 
@@ -56,7 +93,7 @@ echo "${DEBIAN_USER}  ALL=NOPASSD: ALL" >> /etc/sudoers
 
 # Resynchronize the package index files prior to installing the SSH server
 # packages and configuration
-apt-get update
+apt-get update >> "${build_log}"
 
 # Set up SSH server using the tasksel package (which requires /proc to be
 # mounted for some reason) along with the standard packages we would expect
@@ -87,10 +124,10 @@ WantedBy=multi-user.target
 EOF
 
 # Enable the new service
-systemctl enable regenerate_ssh_host_keys
+systemctl enable regenerate_ssh_host_keys >> "${build_log}"
 
 # Some final things to do while still in the chroot environment
-ldconfig
-apt-get clean
+ldconfig >> "${build_log}"
+apt-get clean >> "${build_log}"
 rm -f /tmp/*
 
